"""empty message

Revision ID: 04a7f8c04aad
Revises: c75c752e9aec
Create Date: 2020-11-25 01:18:09.372621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a7f8c04aad'
down_revision = 'c75c752e9aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('secret_key', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administrator_email'), 'administrator', ['email'], unique=True)
    op.create_index(op.f('ix_administrator_secret_key'), 'administrator', ['secret_key'], unique=True)
    op.create_index(op.f('ix_administrator_username'), 'administrator', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_administrator_username'), table_name='administrator')
    op.drop_index(op.f('ix_administrator_secret_key'), table_name='administrator')
    op.drop_index(op.f('ix_administrator_email'), table_name='administrator')
    op.drop_table('administrator')
    # ### end Alembic commands ###
