"""delete

Revision ID: 051f60fffb1e
Revises: 7b843167e474
Create Date: 2020-11-25 00:37:16.616472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051f60fffb1e'
down_revision = '7b843167e474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('product_kind', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
