"""empty message

Revision ID: 52acf7c47321
Revises: 0073e57afce0
Create Date: 2020-11-30 14:41:37.230865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52acf7c47321'
down_revision = '0073e57afce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_cost', sa.REAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_cost')
    # ### end Alembic commands ###
