"""empty message

Revision ID: 663005791abe
Revises: 72808d4f351d
Create Date: 2020-11-26 15:56:06.653300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663005791abe'
down_revision = '72808d4f351d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.Text(), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('product_image', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
