"""empty message

Revision ID: 700c89a1b967
Revises: 52acf7c47321
Create Date: 2020-11-30 14:52:30.071570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700c89a1b967'
down_revision = '52acf7c47321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('incart_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'incart_number')
    # ### end Alembic commands ###
