"""empty message

Revision ID: 72808d4f351d
Revises: 7d191c9f9404
Create Date: 2020-11-26 15:55:32.962582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72808d4f351d'
down_revision = '7d191c9f9404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.TEXT(), nullable=True),
    sa.Column('product_description', sa.TEXT(), nullable=True),
    sa.Column('product_image', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
