"""new products table

Revision ID: 767e04c8e7e4
Revises: 93c5032eafcf
Create Date: 2020-11-23 13:47:00.755877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767e04c8e7e4'
down_revision = '93c5032eafcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products') as batch_op:
        batch_op.drop_column('product_kind')
    # op.drop_column('products', 'product_kind')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_kind', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
