"""new update picture

Revision ID: 7d191c9f9404
Revises: 22fff1ca5b7d
Create Date: 2020-11-25 18:28:56.763760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d191c9f9404'
down_revision = '22fff1ca5b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_image', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_image')
    # ### end Alembic commands ###
