"""new products table

Revision ID: 8853b96fd428
Revises: aa5a316f1e96
Create Date: 2020-11-23 14:08:47.394068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8853b96fd428'
down_revision = 'aa5a316f1e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
