"""new products table

Revision ID: 93c5032eafcf
Revises: fb9676912bb5
Create Date: 2020-11-23 13:44:55.849479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c5032eafcf'
down_revision = 'fb9676912bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_product_kind', table_name='products')
    op.drop_column('products', 'product_kind')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_kind', sa.VARCHAR(length=20), nullable=True))
    op.create_index('ix_products_product_kind', 'products', ['product_kind'], unique=1)
    # ### end Alembic commands ###
