"""added the price of product

Revision ID: a5575f614bd9
Revises: 663005791abe
Create Date: 2020-11-26 17:07:17.656851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5575f614bd9'
down_revision = '663005791abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_price', sa.REAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_price')
    # ### end Alembic commands ###
