"""products_table

Revision ID: aa5a316f1e96
Revises: 767e04c8e7e4
Create Date: 2020-11-23 14:04:52.224405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5a316f1e96'
down_revision = '767e04c8e7e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table('products') as batch_op:
            batch_op.drop_column('product_kind')
    # op.drop_column('products', 'product_kind')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_kind', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
