"""create transaction table with foreign key

Revision ID: bab7707a8084
Revises: a5575f614bd9
Create Date: 2020-11-29 21:56:16.667161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab7707a8084'
down_revision = 'a5575f614bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.Text(), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('product_image', sa.String(length=20), nullable=False),
    sa.Column('product_price', sa.REAL(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('order_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
