"""add product_description to products

Revision ID: dc99c502339b
Revises: 04a7f8c04aad
Create Date: 2020-11-25 18:24:57.788680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc99c502339b'
down_revision = '04a7f8c04aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_description')
    # ### end Alembic commands ###
